
CREATE TABLE inmobix.realstates (
    id bigint NOT NULL,
    address character varying(255),
    bathrooms integer NOT NULL,
    bedrooms integer NOT NULL,
    description character varying(255),
    has_parking boolean NOT NULL,
    picture character varying(255),
    price bigint NOT NULL,
    title character varying(255)
);

ALTER TABLE inmobix.realstates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME inmobix.realstates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (1, 'Calle Primavera 123, Ciudad Jardín', 2, 3, 'Amplia casa con jardín y terraza, ideal para familias. Recientemente renovada.', true, NULL, 250000, 'Acogedora casa en zona residencial');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (2, 'Avenida Central 456, Centro Metropolitano', 1, 2, 'Piso completamente amueblado cerca de transporte público y centros comerciales.', false, NULL, 180000, 'Moderno apartamento céntrico');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (3, 'Bulevar Costero 789, Zona Premium', 4, 5, 'Exclusiva propiedad con vistas al mar, acabados de alta gama y seguridad 24h.', true, NULL, 850000, 'Villa de lujo con piscina');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (4, 'Calle Universitaria 321, Distrito Estudiantil', 1, 1, 'Pequeño pero funcional, incluye todos los servicios básicos. Perfecto para universitarios.', false, NULL, 95000, 'Estudio económico para estudiantes');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (5, 'Camino Rural Km 5, Valle Verde', 3, 4, 'Propiedad rústica con 2 hectáreas de terreno, ideal para proyectos agrícolas o turísticos.', true, NULL, 320000, 'Casa rural con terreno');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (6, 'Calle Factory 101, Barrio Moderno', 1, 1, 'Espacio abierto con detalles industriales, excelente iluminación natural y techos altos.', true, NULL, 295000, 'Loft industrial en zona trendy');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (7, 'Avenida Horizonte 1500, Torre Mirador', 3, 4, 'Ático de lujo con terraza privada, jardinera interior y acceso directo al ascensor.', true, NULL, 1200000, 'Penthouse con vista panorámica');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (8, 'Calle Verde 88, EcoResidencial', 2, 3, 'Construcción sostenible con paneles solares, aislamiento térmico y huerto urbano.', true, NULL, 420000, 'Casa minimalista ecológica');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (9, 'Pasaje Urbano 22, MicroLiving District', 1, 1, 'Espacio pequeño con acabados contemporáneos y cocina inteligente.', false, NULL, 110000, 'Departamento compacto pero moderno');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (10, 'Calle Roble 678, Jardines del Sol', 3, 4, 'Vivienda de dos plantas con patio trasero, ideal para reuniones y mascotas.', true, NULL, 310000, 'Dúplex familiar con patio amplio');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (11, 'Calle Patrimonio 14, Casco Antiguo', 2, 3, 'Edificación del siglo XIX renovada respetando su arquitectura original.', false, NULL, 560000, 'Casa histórica restaurada');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (12, 'Camino Pinar 9, Bosque Silvestre', 1, 2, 'Aislada y rodeada de naturaleza, con chimenea y ventanales panorámicos.', true, NULL, 275000, 'Cabaña en bosque privado');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (13, 'Boulevard Empresarial 500, Distrito Corporativo', 4, 4, 'Propiedad moderna con sala multimedia, oficina privada y cochera doble.', true, NULL, 650000, 'Residencia ejecutiva premium');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (14, 'Avenida Popular 233, Zona Urbana', 1, 1, 'Loft sencillo con buena iluminación y acceso a transporte público.', false, NULL, 89000, 'Apartamento tipo loft económico');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (15, 'Calle Los Laureles 10, Colonia Privada', 5, 6, 'Amplio jardín, piscina climatizada y zona deportiva totalmente equipada.', true, NULL, 1500000, 'Mansión con cancha de tenis');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (16, 'Sendero Nevado 44, Altos del Frío', 2, 3, 'Diseño rústico con balcones de madera y vistas a la montaña.', true, NULL, 380000, 'Chalet alpino con chimenea');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (17, 'Calle Creativa 301, Barrio Artístico', 1, 1, 'Murales pintados a mano, iluminación LED dinámica y espacio adaptable.', false, NULL, 155000, 'Departamento joven y artístico');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (18, 'Circuito Modular 8, Villas Flex', 2, 2, 'Construcción modular con posibilidad de ampliar habitaciones fácilmente.', true, NULL, 215000, 'Casa modular ampliable');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (19, 'Avenida Magnolia 77, Suburbia Norte', 2, 3, 'Casa cómoda con ático amplio ideal para estudio o cuarto de juegos.', true, NULL, 275000, 'Hogar suburbano con ático');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (20, 'Camino Campo Abierto 12, Rancho Dorado', 3, 4, 'Terreno amplio con establo y espacio para criar caballos.', true, NULL, 480000, 'Residencia campestre con establo');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (21, 'Calle Turística 17, Zona Hotelera', 1, 1, 'Espacio pequeño completamente equipado para estancias cortas.', false, NULL, 98000, 'Mini loft para turistas');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (22, 'Calle Futuro 404, Ciudad Digital', 3, 3, 'Control de luces, clima y seguridad desde el móvil.', true, NULL, 520000, 'Casa inteligente totalmente automatizada');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (23, 'Avenida Ribera 112, Costa Azul', 2, 2, 'Acabados elegantes, balcón amplio y acceso directo al malecón.', false, NULL, 210000, 'Apartamento con vista al río');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (24, 'Calle Vintage 55, Barrio Bohemio', 2, 3, 'Decoración retro, vigas expuestas y mucha luz natural.', true, NULL, 330000, 'Dúplex vintage con suelo de madera');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (25, 'Playa Serena 9, Costa Blanca', 1, 2, 'A pocos metros del mar, ambiente tranquilo y brisa constante.', true, NULL, 260000, 'Cabaña playera con hamacas');
INSERT INTO inmobix.realstates (id, address, bathrooms, bedrooms, description, has_parking, picture, price, title) VALUES (26, 'Calle Metropolis 202, Centro Urbano', 4, 4, 'Sótano convertido en sala de cine, diseño elegante y jardín vertical.', true, NULL, 740000, 'Casa urbana de lujo con sótano');

SELECT pg_catalog.setval('inmobix.realstates_id_seq', 26, true);

ALTER TABLE ONLY inmobix.realstates
    ADD CONSTRAINT realstates_pkey PRIMARY KEY (id);
